application: feras-uk
version: 3
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /scripts/hi
  script: scripts.hello.application

- url: /scripts/(.*)
  script: scripts.\1.application

- url: /html
  static_dir: static/html

- url: /stylesheets
  static_dir: static/stylesheets

- url: /images
  static_dir: static/images

- url: /
  static_files: static/html/index.html
  upload: index.html

libraries:
- name: webapp2
  version: "2.5.2"
